name: ChunkSaver
version: 1.0.0
description: Saves modified chunks on a timer
main: io.github.ratismal.chunksaver.ChunkSaver
author: Ratismal
permissions:
  chunksaver.see:
    description: Permission required to see operation results
    default: op